# Generated by Django 3.2.7 on 2021-11-06 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abundancias',
            fields=[
                ('id_abundancia', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('tax_abundancia', models.TextField(blank=True, null=True)),
                ('num_abundancia', models.FloatField(blank=True, null=True)),
                ('ran_abundancia', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'abundancias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AbundanciasEcosistemas',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'abundancias_ecosistemas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AbundanciasUh',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'abundancias_uh',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id_actividad', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_actividad', models.CharField(blank=True, max_length=100, null=True)),
                ('sigla_actividad', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'actividades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActividadesNoPermitidadMacro',
            fields=[
                ('id_zona_macrona', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('actividades_no_permitidas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actividades_no_permitidad_macro',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActividadesNoPermitidasZona',
            fields=[
                ('id_zona_prot_est', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('actividades_no_permitidas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actividades_no_permitidas_zona',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActividadesPermitidadMacrona',
            fields=[
                ('id_zona_macrona', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('actividades_permitidas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actividades_permitidad_macrona_',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActividadesPermitidadZonasCo',
            fields=[
                ('id_zona_conservacion', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('actividades_permitidas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actividades_permitidad_zonas_co',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActividadesPermitidadZonasPr',
            fields=[
                ('id_zona_prot_est', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('actividades_permitidas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actividades_permitidad_zonas_pr',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActividadesPermitidadZonasRe',
            fields=[
                ('id_zona_restauracion', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('actividades_permitidas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'actividades_permitidad_zonas_re',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ActividaNoPermitidaZonasRes',
            fields=[
                ('id_zona_restauracion', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('actividades_permitidas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activida_no_permitida_zonas_res',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ArbolAlimentoPericos',
            fields=[
                ('id_arbol', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('especie_arbol', models.TextField(blank=True, null=True)),
                ('mes_epoca', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'arbol_alimento_pericos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreanaturalGeologia',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('hec_geologia', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'areanatural_geologia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreanaturalGeomorfologia',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('hec_geologia', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'areanatural_geomorfologia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreanaturalLocacion',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('km_cuadrados', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'areanatural_locacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreanaturalSuelo',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('hec_geologia', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'areanatural_suelo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id_area', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('cat_area', models.TextField(blank=True, null=True)),
                ('nom_area', models.CharField(blank=True, max_length=255, null=True)),
                ('fec_creacion', models.DateField(blank=True, null=True)),
                ('acu_resolucion_area', models.TextField(blank=True, null=True)),
                ('aut_competente_area', models.TextField(blank=True, null=True)),
                ('superfici_area', models.TextField(blank=True, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'areas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreasNaturalesConservacion',
            fields=[
                ('id_areanatural', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nombre_area', models.TextField(blank=True, null=True)),
                ('desc_area', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'areas_naturales_conservacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreasNaturalesCorredorEcolog',
            fields=[
                ('id_area_corredor', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('asp_min_cap_inst', models.TextField(blank=True, null=True)),
                ('analisis', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'areas_naturales_corredor_ecolog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AreaVegetal',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('covertura_vegetal', models.TextField(blank=True, null=True)),
                ('hectareas', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'area_vegetal',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BenCorredoresEcologicos',
            fields=[
                ('id_beneficio', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nombre_beneficio', models.TextField(blank=True, null=True)),
                ('descripcion_beneficio', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ben_corredores_ecologicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Biomas',
            fields=[
                ('id_bioma', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_bioma', models.CharField(blank=True, max_length=100, null=True)),
                ('sigla_bioma', models.CharField(blank=True, max_length=50, null=True)),
                ('des_altitudinal_bioma', models.FloatField(blank=True, null=True)),
                ('has_altitudinal_bioma', models.FloatField(blank=True, null=True)),
                ('remanencia', models.FloatField(blank=True, null=True)),
                ('ext_bioma', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'biomas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BiomasCantones',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'biomas_cantones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BiomasEcosistemas',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'biomas_ecosistemas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BiomasEspecies',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'biomas_especies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bosques',
            fields=[
                ('id_bosque', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_bosque', models.CharField(blank=True, max_length=100, null=True)),
                ('pro_administrador_bosque', models.TextField(blank=True, null=True)),
                ('localizacion_area', models.TextField(blank=True, null=True)),
                ('micro_cuencas', models.TextField(blank=True, null=True)),
                ('reg_oficial_bosque', models.TextField(blank=True, null=True)),
                ('hec_bosque', models.FloatField(blank=True, null=True)),
                ('vegetacion_remanente', models.FloatField(blank=True, null=True)),
                ('altitud_max', models.FloatField(blank=True, null=True)),
                ('altitud_min', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bosques',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CantonArea',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'canton_area',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CantonBosque',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'canton_bosque',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CantonEcosistema',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'canton_ecosistema',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cantones',
            fields=[
                ('id_canton', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_canton', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'cantones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CantonesRios',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cantones_rios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CantonesUnidadesHidrograficas',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'cantones_unidades_hidrograficas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CircuitosIntegracionBiolog',
            fields=[
                ('id_circuito', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre_circuito', models.CharField(blank=True, max_length=100, null=True)),
                ('desc_circuito', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'circuitos_integracion_biolog',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clases',
            fields=[
                ('id_clase', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_clase', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('abund_clase', models.CharField(blank=True, max_length=100, null=True)),
                ('num_ord_clase', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'clases',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Distribuciones',
            fields=[
                ('id_distribucion', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_distribucion', models.CharField(blank=True, max_length=200, null=True)),
                ('sigla_distribucion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'distribuciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ecosistemas',
            fields=[
                ('id_ecosistema', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_ecosistema', models.CharField(blank=True, max_length=250, null=True)),
                ('cod_ecosistema', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ecosistemas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Endemismos',
            fields=[
                ('id_endemismo', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_endemismo', models.CharField(blank=True, max_length=100, null=True)),
                ('sigla_endemismo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'endemismos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EspecieGremioalimentario',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'especie_gremioalimentario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EspecieLocaciones',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'especie_locaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EspecieRegistros',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'especie_registros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Especies',
            fields=[
                ('id_especie', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_especie', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('rango_altitudinal', models.TextField(blank=True, null=True)),
                ('ubicacion', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('nom_cientifico', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_ingles', models.CharField(blank=True, max_length=100, null=True)),
                ('anio_descubrimiento', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'especies',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EspeciesActividades',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'especies_actividades',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EspeciesDistribucion',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'especies_distribucion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EspeciesLocalidadesMuestreo',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'especies_localidades_muestreo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EspeciesTiposvegetacion',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'especies_tiposvegetacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstacionesMuestreos',
            fields=[
                ('id_em', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_em', models.CharField(blank=True, max_length=100, null=True)),
                ('nom_formal_em', models.CharField(blank=True, max_length=255, null=True)),
                ('cod_em', models.CharField(blank=True, max_length=100, null=True)),
                ('ind_shannon_em', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estaciones_muestreos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoConservacion',
            fields=[
                ('id_estado_conservacion', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(blank=True, max_length=100, null=True)),
                ('sigla', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estado_conservacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoConservacionCuerposAgu',
            fields=[
                ('id_rio', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('codigo', models.TextField(blank=True, null=True)),
                ('bmwp_col', models.IntegerField(blank=True, null=True)),
                ('calidad_agua', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estado_conservacion_cuerpos_agu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstudiosPericos',
            fields=[
                ('id_estudioperico', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('localidad_especie', models.IntegerField(blank=True, null=True)),
                ('numero_pericos_especie', models.IntegerField(blank=True, null=True)),
                ('grupo_especie', models.IntegerField(blank=True, null=True)),
                ('anio_estudio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'estudios_pericos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Familias',
            fields=[
                ('id_familia', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_familia', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'familias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Fisiotopico',
            fields=[
                ('id_fisiotopico', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nombre_fisiotopico', models.TextField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('recomendacion_y_uso', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fisiotopico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Flora',
            fields=[
                ('id_flora', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_flora', models.CharField(blank=True, max_length=250, null=True)),
                ('tipo_flora', models.CharField(blank=True, max_length=50, null=True)),
                ('etimologia_flora', models.TextField(blank=True, null=True)),
                ('diagnosis_flora', models.TextField(blank=True, null=True)),
                ('comentarios_taxonomicos_flora', models.TextField(blank=True, null=True)),
                ('distribucion_composicion_flora', models.TextField(blank=True, null=True)),
                ('autor_flora', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'flora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FloraBiomas',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'flora_biomas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FloraEndemicaAmenazada',
            fields=[
                ('id_flora', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nombre_cientifico_endemica_amenaza', models.TextField(blank=True, null=True)),
                ('uicn_cites_endemica_amenaza', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'flora_endemica_amenazada',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FloraImagen',
            fields=[
                ('id_flora_imagen', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('imagenflora', models.ImageField(blank=True, null=True, upload_to='flora')),
                ('tipo_flora_imagen', models.CharField(blank=True, max_length=100, null=True)),
                ('autor_flora_imagen', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'flora_imagen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FloraLocaciones',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'flora_locaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id_genero', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_genero', models.CharField(blank=True, max_length=45, null=True)),
                ('etimologia_genero', models.TextField(blank=True, null=True)),
                ('diagnosis_genero', models.TextField(blank=True, null=True)),
                ('comentarios_taxonomico_genero', models.TextField(blank=True, null=True)),
                ('distribucion_composicion_genero', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'genero',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GeneroFlora',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'genero_flora',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Geologias',
            fields=[
                ('id_geologia', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_geologia', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'geologias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Geomorfologia',
            fields=[
                ('id_geomorfologia', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_geomorfologia', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'geomorfologia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='GremioAlimentario',
            fields=[
                ('id_gremio_alimentario', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nom_gremio_alimentario', models.CharField(blank=True, max_length=200, null=True)),
                ('sigla_gremio_alimentario', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'gremio_alimentario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id_imagen', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='especies')),
                ('tipo_imagen', models.CharField(blank=True, max_length=100, null=True)),
                ('autor_imagen', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'imagenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagenesAbundancia',
            fields=[
                ('id_imagen', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('imagen_abundancia', models.ImageField(blank=True, null=True, upload_to='abundancias')),
            ],
            options={
                'db_table': 'imagenes_abundancia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImagenesBiomas',
            fields=[
                ('id_imagenbioma', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('url_imagen', models.ImageField(blank=True, null=True, upload_to='biomas')),
                ('autor', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'imagenes_biomas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Infraordenes',
            fields=[
                ('id_infraorden', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_infraorden', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'infraordenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LineaCorredoresEcologicos',
            fields=[
                ('id_linea', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_linea_corredores_ecologicos', models.TextField(blank=True, null=True)),
                ('descripcion_linea_corredores_ecologicos', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'linea_corredores_ecologicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locaciones',
            fields=[
                ('id_locacion', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_locacion', models.CharField(blank=True, max_length=100, null=True)),
                ('sigla_locacion', models.CharField(blank=True, max_length=50, null=True)),
                ('alt_locacion', models.FloatField(blank=True, null=True)),
                ('coordenadas', models.TextField(blank=True, null=True)),
                ('latitud_locacion', models.FloatField(blank=True, null=True)),
                ('longitud_locacion', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'locaciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='LocalidadesMuestreo',
            fields=[
                ('id_muestreo', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('num_muestreo', models.FloatField(blank=True, null=True)),
                ('nom_muestreo', models.CharField(blank=True, max_length=200, null=True)),
                ('des_muestreo', models.TextField(blank=True, null=True)),
                ('log_muestreo', models.FloatField(blank=True, null=True)),
                ('lat_muestreo', models.FloatField(blank=True, null=True)),
                ('alt_muestreo', models.FloatField(blank=True, null=True)),
                ('tipo_animal_muestreo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'localidades_muestreo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MicrocuencasPorZonasProtecci',
            fields=[
                ('id_microcuenca', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre_microcuenca', models.TextField(blank=True, null=True)),
                ('superficie_microcuenca', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('zona1_micro', models.IntegerField(blank=True, null=True)),
                ('zona2_micro', models.IntegerField(blank=True, null=True)),
                ('zona3_micro', models.TextField(blank=True, null=True)),
                ('zona4_micro', models.IntegerField(blank=True, null=True)),
                ('zona5_micro', models.IntegerField(blank=True, null=True)),
                ('zona6_micro', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'microcuencas_por_zonas_protecci',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MigracionAves',
            fields=[
                ('id_migracion', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nom_migracion', models.CharField(blank=True, max_length=200, null=True)),
                ('sigla', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'migracion_aves',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Nichotrofico',
            fields=[
                ('id_nicho_trofico', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_nicho', models.CharField(blank=True, max_length=150, null=True)),
                ('sigla_nicho', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'nichotrofico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id_orden', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_orden', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'ordenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenesBiomas',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ordenes_biomas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrdenesFamilias',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('num_generos', models.IntegerField(blank=True, null=True)),
                ('num_especies', models.IntegerField(blank=True, null=True)),
                ('porcentaje', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'ordenes_familias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Paisajes',
            fields=[
                ('id_paisaje', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_paisaje', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'paisajes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parroquias',
            fields=[
                ('id_parroquia', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_parroquia', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'parroquias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ParroquiasRios',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'parroquias_rios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Personas',
            fields=[
                ('id_persona', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_persona', models.CharField(blank=True, max_length=255, null=True)),
                ('ape_persona', models.CharField(blank=True, max_length=255, null=True)),
                ('tipo', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'personas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PisosZeogeograficos',
            fields=[
                ('id_pisozeogeografico', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_pisozeogeografico', models.CharField(blank=True, max_length=200, null=True)),
                ('sigla_pisozeogeografico', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'pisos_zeogeograficos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincias',
            fields=[
                ('id_provincia', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_provincia', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'provincias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RegionesNaturalez',
            fields=[
                ('id_zona', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nombre_zona', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'regiones_naturalez',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Registros',
            fields=[
                ('id_registro', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_registro', models.CharField(blank=True, max_length=100, null=True)),
                ('literal', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'registros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Relieves',
            fields=[
                ('id_relieve', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('ubicacion_relieve', models.TextField(blank=True, null=True)),
                ('longitud_min', models.TextField(blank=True, null=True)),
                ('longitud_max', models.TextField(blank=True, null=True)),
                ('territorio_relieve', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'relieves',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rios',
            fields=[
                ('id_rio', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_rio', models.CharField(blank=True, max_length=100, null=True)),
                ('categoria', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'rios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ServiciosEcosistemicos',
            fields=[
                ('id_servicioecosistemico', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_servicioecosistemico', models.TextField(blank=True, null=True)),
                ('hec_servicioecosistemico', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('por_servicioecosistemico', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'servicios_ecosistemicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='SitiosMuestreoBioecologia',
            fields=[
                ('id_sitio', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('bioma', models.TextField(blank=True, null=True)),
                ('coordenadas', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sitios_muestreo_bioecologia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subfamilias',
            fields=[
                ('id_subfamilia', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_subfamilia', models.CharField(blank=True, max_length=100, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'subfamilias',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subtribu',
            fields=[
                ('id_subtribu', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_subtribu', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subtribu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Suelos',
            fields=[
                ('id_suelos', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_suelos', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'suelos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TelemetriaPericos',
            fields=[
                ('id_telemetria', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('num_pericos', models.IntegerField(blank=True, null=True)),
                ('cant_telemetrica', models.IntegerField(blank=True, null=True)),
                ('estado_grupo_perico', models.TextField(blank=True, null=True)),
                ('distancia_vuelo_max', models.TextField(blank=True, null=True)),
                ('distancia_vuelo_promedio', models.TextField(blank=True, null=True)),
                ('tiempo_estancia_bosques_max', models.TextField(blank=True, null=True)),
                ('tiempo_estancia_bosques_pro', models.TextField(blank=True, null=True)),
                ('tiempo_estancia_pastos_max', models.TextField(blank=True, null=True)),
                ('tiempo_estancia_pastos_pro', models.TextField(blank=True, null=True)),
                ('habitat_bosques', models.TextField(blank=True, null=True)),
                ('habitat_pasto_arbolado', models.TextField(blank=True, null=True)),
                ('habitat_area_vida_semanal', models.TextField(blank=True, null=True)),
                ('habitat_area_vida_diaria', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'telemetria_pericos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TiposVegetacion',
            fields=[
                ('id_tipovegetacion', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_tipovegetacion', models.CharField(blank=True, max_length=100, null=True)),
                ('sigla_tipovegetacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'tipos_vegetacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tribu',
            fields=[
                ('id_tribu', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_tribu', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tribu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadesFisiotopicos',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('hectareas', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'unidades_fisiotopicos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadesHidrograficas',
            fields=[
                ('id_uh', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nom_uh', models.CharField(blank=True, max_length=200, null=True)),
                ('cod_uh', models.IntegerField(blank=True, null=True)),
                ('riqueza_uh', models.FloatField(blank=True, null=True)),
                ('abundancia_uh', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'unidades_hidrograficas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id_user', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('email_user', models.TextField(blank=True, null=True)),
                ('image_user', models.TextField(blank=True, null=True)),
                ('password_user', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_user', models.CharField(blank=True, max_length=50, null=True)),
                ('create_at_user', models.DateTimeField(blank=True, null=True)),
                ('modif_at_user', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuariosApp',
            fields=[
                ('idusuario', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=45, unique=True)),
                ('email', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'usuarios_app',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VariablesClimaticas',
            fields=[
                ('id_variable', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('codigo', models.TextField(blank=True, null=True)),
                ('variable', models.TextField(blank=True, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('importancia', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'variables_climaticas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZonasCorredorEcologico',
            fields=[
                ('id_zona', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nombre_zona', models.CharField(blank=True, max_length=200, null=True)),
                ('hectarias_zona', models.FloatField(blank=True, null=True)),
                ('porcentaje_zona', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zonas_corredor_ecologico',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZonasVida',
            fields=[
                ('id_zona', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('nombre_zona', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'zonas_vida',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ZonificacionMicrocuencaRioCa',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('nom_macrozonas', models.TextField(blank=True, null=True)),
                ('recomendacion_de_uso', models.TextField(blank=True, null=True)),
                ('hectara', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
                ('porcentaje', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'zonificacion_microcuenca_rio_ca',
                'managed': False,
            },
        ),
    ]
